alias:
    - confuzzius
    - confuzziusBI
    - conkas
    - detecti
    - etainter
    - ethainter
    - ethersolve
    - ethertrust
    - ethlint
    - ethor
   # - gigahorse
    - honeybadger
    - ityfuzz
    - madmax
    - maian
    - manticore
    - mythril
    - osiris
    - oyente
    - pakala
    - rnvuldet
    - scanalyzer
    - securify
    - semgrep
    - sfuzz
    - siguard
    - slither
    - smartcheck
    - solhint
    - soliditycheck
    - teether
    - vandal
   # - vulpedia
