name: achecker # optional
version: 0.1 # version number, commit id, ... (optional)
origin: https://github.com/DependableSystemsLab/Achecker # optional
info: static analysis tool for detecting access control vulnerabilities in smart contracts # optional
image: geriul/achecker:latest # id of Docker image (mandatory)
#output: /app/output.project.json
bin: scripts # folder with programs that will be accessible in the Docker container
# add the section below if the tool is able to analyse Solidity source code
# solidity:
#     entrypoint: "'$BIN/do_solidity.sh' '$FILENAME' '$TIMEOUT' '$BIN'"
#     solc: yes
bytecode:
    entrypoint: "'$BIN/do_bytecode.sh' '$FILENAME' '$TIMEOUT' '$BIN'"
