import sb.parse_utils # for sb.parse_utils.init(...)
import io, tarfile    # if the output parameter is used

from tools.sfuzz.parser import vulnerabilities

VERSION: str = "2022/08/15"
"""identify the version of the parser, e.g. '2022/08/15'"""

FINDINGS: set[str]  = {
    "Unbounded-Loop",
    "DoS-With-Failed-Call",}
"""set of strings: all possible findings, of which 'findings' below will be a subset"""


def parse(exit_code, log, output):
    """
    Analyse the result of the tool tun.

    :param exit_code: int|None, exit code of Docker run (None=timeout)
    :param log: list[str], stdout/stderr of Docker run
    :param output: bytes, tar archive of files generated by the tool (if specified in config.yaml)

    :return: tuple[findings: list[dict], infos: set[str], errors: set[str], fails: set[str]]
      findings identifies the major observations of the tool,
      infos contains any messages generated by the tool that might be of interest,
      errors lists the error messages deliberately generated by the tool,
      fails lists exceptions and other events not expected by the tool,
      analysis contains any analysis results worth reporting
    """

    findings, infos = [], set()
    errors, fails = sb.parse_utils.errors_fails(exit_code, log)
    #errors, fails = set(), set()
    # Parses the output for common Python/Java/shell exceptions (returned in 'fails')

    vulnerability = None
    message = None
    function_name = None
    function_address = None
    found = False

    for line in log:
        # analyse stdout/stderr of the Docker run
        if "Unbounded loop condition in function" in line:
            vulnerability = "Unbounded-Loop"
            message = "Unbounded loop condition found"
            function_name = line.split(":")[1].strip()
            found = True
        elif "DoS-With-Failed-Call in function" in line:
            vulnerability = "DoS-With-Failed-Call"
            message = "DoS-With-Failed-Call found"
            function_name = line.split(":")[1].strip()
            found = True
        elif line.startswith("("):
            function_address = line.replace("(", "").replace(")", "").replace(":", "").strip().split(" ")[0].strip()
            if found:
                findings.append({
                    "name": vulnerability,
                    "function": function_name,
                    "address": function_address,
                    "message": message,
                    "severity": "high",
                })
                vulnerability = None
                message = None
                function_name = None
                function_address = None
                found = False

    return findings, infos, errors, fails
    """
    findings is a list of issues. Each issue is a dict with the following fields.
    name: str
        mandatory. Identifies the type of issue
    filename: str
        optional. Path of file processed. As this is the path within
        the docker image, it will be replaced by the external filename,
        after parsing.
    contract: str
        optional. Name of contract within the file (for source code)
    function: str
        optional. Name/header/signature of function containing the issue
    line: int
        optional. Line number of issue in source code, starting with 1
    column: int
        optional. Column of issue in source code, starting with 1
    line_end: int
        optional. Last line of the source code, where issue occurs.
    column_end: int
        optional. Last column of the source code, where issue occurs.
    address: int
        optional. Address of instruction in the bytecode, where issue occurs, starting with 0
    address_end: int
        optional. Address of last instruction in the bytecode, where issue occurs, starting with 0
    exploit: Any
        optional. Information on a potential exploit, e.g. a list of transactions
    level: str
        optional. type of issue, e.g. recommendation, warning, error
    severity: str
        optional. Severity of issue, e.g. low, medium, high
    message: str
        optional. Description of the issue

    If missing, the fields severity, classification, method, descr_short,
    descr_long will be taken from the file findings.yaml in the tools
    directory (if it exists), with "name" serving as the key.
    """



# def main():
#     file = open(file_name, "r")
#     findings, infos, errors, fails = parse(None, file, None)
#     for line in findings:
#         print(line)
#
# if __name__ == '__main__':
#     main()