import sb.parse_utils # for sb.parse_utils.init(...)
import io, tarfile, re   # if the output parameter is used

VERSION: str = "11/12/2025"

FINDINGS = {
    "Misuse of constructor", 
    "Function without visibility", 
    "Storage variable shadowing confusion", 
    "Type casting to arbitrary contracts", 
    "Inheritance order confusion", 
    "Uninitialized storage pointer", 
    "Typo of the += operator", 
    "Usage of Deprecated API"
}

def parse(exit_code, log, output):
    """
    Analyse the result of the tool tun.

    :param exit_code: int|None, exit code of Docker run (None=timeout)
    :param log: list[str], stdout/stderr of Docker run
    :param output: bytes, tar archive of files generated by the tool (if specified in config.yaml)

    :return: tuple[findings: list[dict], infos: set[str], errors: set[str], fails: set[str]]
      findings identifies the major observations of the tool,
      infos contains any messages generated by the tool that might be of interest,
      errors lists the error messages deliberately generated by the tool,
      fails lists exceptions and other events not expected by the tool,
      analysis contains any analysis results worth reporting
    """

    findings, infos = [], set()
    errors, fails = sb.parse_utils.errors_fails(exit_code, log)
    # Parses the output for common Python/Java/shell exceptions (returned in 'fails')

    found_func_error = False
    found_var_error  = False

    try:
        with io.BytesIO(output) as o, tarfile.open(fileobj=o) as tar:
            pattern = re.compile(
                r'^Analyzed\s*:\s*(.+?)\n\nDetail Information\n\n$',
                re.DOTALL
            )

            contents_bytes = tar.extractfile("test_result.txt").read()
            contents = contents_bytes.decode('utf-8', errors='ignore')

            # 1. Caso: output vuoto + controllo errori nel log
            m = pattern.search(contents)
            if m:
                if not log[0].startswith("The command 'runTest' took"):
                    for line in log:
                        s = line.strip()

                        # Caso 1 — Error in Function Definition
                        if "Error in Function Definition" in s and not found_func_error:
                            errors.add(s)
                            found_func_error = True

                        # Caso 2 — Error in VariableDeclaration
                        elif "Error in VariableDeclaration" in s and not found_var_error:
                            errors.add(s)
                            found_var_error = True

                        # Se hai trovato entrambi puoi anche uscire dal loop
                        if found_func_error and found_var_error:
                            break
                return findings, infos, errors, fails

            # 2. Caso: output pieno + controllo errori nel log
            for line in contents.splitlines():
                line = line.strip()

                if not line:
                    continue

                if line.startswith("Uninitialized storage pointer"):
                    findings.append({"name": "Uninitialized storage pointer"})

                if line.startswith("Function without visibility"):
                    findings.append({"name": "Function without visibility"})
                
                if line.startswith("Inheritance order confusion"):
                    findings.append({"name": "Inheritance order confusion"})
                
                if line.startswith("Typo of the += operator"):
                    findings.append({"name": "Typo of the += operator"})
                
                if line.startswith("Storage variable shadowing confusion"):
                    findings.append({"name": "Storage variable shadowing confusion"})
                
                if line.startswith("Misuse of constructor"):
                    findings.append({"name": "Misuse of constructor"})
                
                if line.startswith("Type casting to arbitrary contracts"):
                    findings.append({"name": "Type casting to arbitrary contracts"})
                
                if line.startswith("Usage of Deprecated API"):
                    findings.append({"name": "Usage of Deprecated API"})
            
            if not log[0].startswith("The command 'runTest' took"):
                for line in log:
                    s = line.strip()

                    # Caso 1 — Error in Function Definition
                    if "Error in Function Definition" in s and not found_func_error:
                        errors.add(s)
                        found_func_error = True

                    # Caso 2 — Error in VariableDeclaration
                    elif "Error in VariableDeclaration" in s and not found_var_error:
                        errors.add(s)
                        found_var_error = True

                    # Se hai trovato entrambi puoi anche uscire dal loop
                    if found_func_error and found_var_error:
                        break
                            
    except Exception as e:
        fails.add(f"error parsing results: {e}")

    return findings, infos, errors, fails
    """
    findings is a list of issues. Each issue is a dict with the following fields.
    name: str
        mandatory. Identifies the type of issue
    filename: str
        optional. Path of file processed. As this is the path within
        the docker image, it will be replaced by the external filename,
        after parsing.
    contract: str
        optional. Name of contract within the file (for source code)
    function: str
        optional. Name/header/signature of function containing the issue
    line: int
        optional. Line number of issue in source code, starting with 1
    column: int
        optional. Column of issue in source code, starting with 1
    line_end: int
        optional. Last line of the source code, where issue occurs.
    column_end: int
        optional. Last column of the source code, where issue occurs.
    address: int
        optional. Address of instruction in the bytecode, where issue occurs, starting with 0
    address_end: int
        optional. Address of last instruction in the bytecode, where issue occurs, starting with 0
    exploit: Any
        optional. Information on a potential exploit, e.g. a list of transactions
    level: str
        optional. type of issue, e.g. recommendation, warning, error
    severity: str
        optional. Severity of issue, e.g. low, medium, high
    message: str
        optional. Description of the issue

    If missing, the fields severity, classification, method, descr_short,
    descr_long will be taken from the file findings.yaml in the tools
    directory (if it exists), with "name" serving as the key.
    """

